### ISSUE TITLE
Scale Helper Tool

### ISSUE THREAD

**Issue by clsource** [djdiskmachine/LittleGPTracker#119]
Borrowing ideas from the [Lovely Composer](https://doc1oo.github.io/LovelyComposerDocs/en/manual.html#scale-function) tool. They have a "Scale Function" which helps in song composition.

Example scale: `C F G`

Will only allow notes C, F and G in any octave for this phrase

Some ideas for implementing this:

- The scales will be defined inside config.xml or a new file named scales.xml
- In the phrase screen you can select the scale and will limit the note input to the notes available in the scale.

This is just an aid for writing notes.

Sample `scales.xml`

```xml
<SCALES>
    <SCALE value="C Major">
        <NOTE value="C" />
        <NOTE value="D" />
        <NOTE value="E" />
        <NOTE value="F" />
        <NOTE value="G" />
        <NOTE value="A" />
         <NOTE value="B" />
    </SCALE>
   <SCALE value="C Minor">
        <NOTE value="C" />
        <NOTE value="D" />
        <NOTE value="D#" />
        <NOTE value="F" />
        <NOTE value="G" />
        <NOTE value="G#" />
        <NOTE value="A#" />
    </SCALE>
   <SCALE value="Black Keys">
        <NOTE value="C#" />
        <NOTE value="D#" />
        <NOTE value="F#" />
        <NOTE value="G#" />
        <NOTE value="A#" />
    </SCALE>
   <!-- https://pianoencyclopedia.com/scales/ryukyu/C-ryukyu.html -->
    <SCALE value="C Ryukyu">
        <NOTE value="C" />
        <NOTE value="E" />
        <NOTE value="F" />
        <NOTE value="G" />
        <NOTE value="B" />
    </SCALE>
  <!-- https://pianoencyclopedia.com/scales/yo-shomyo-gagaku/C-yo-shomyo-gagaku.html -->
    <SCALE value="C Gagaku">
        <NOTE value="C" />
        <NOTE value="D" />
        <NOTE value="F" />
        <NOTE value="G" />
        <NOTE value="A" />
    </SCALE>
    <!-- https://pianoencyclopedia.com/scales/whole-tone-i/C-whole-tone-i.html -->
    <SCALE value="C WholeTone">
        <NOTE value="C" />
        <NOTE value="D" />
        <NOTE value="E" />
        <NOTE value="F#" />
        <NOTE value="G#" />
        <NOTE value="A#" />
    </SCALE>
  <!-- https://www.scales-chords.com/chord/piano/Daug -->
   <SCALE value="D aug">
        <NOTE value="D" />
        <NOTE value="F#" />
        <NOTE value="A#" />
    </SCALE>
    <!-- https://pianoencyclopedia.com/scales/lydian/C-lydian.html -->
    <SCALE value="C Lydian">
        <NOTE value="C" />
        <NOTE value="D" />
        <NOTE value="E" />
        <NOTE value="F#" />
        <NOTE value="G" />
        <NOTE value="A" />
        <NOTE value="B" />
    </SCALE>
</SCALE>
```

**Comment by clsource** [comment]
The idea can be executed like this
In the Phrase Screen
![imagen](https://github.com/user-attachments/assets/800c4612-5f8e-4232-a6f4-c261fa320115)

Press `L_SHOULDER` and `Left or Right`. This will navigate the available chords and restrict the possible notes on any instrument.

So the chord pattern tool can be applied to any instrument since its a handy tool in Phrase Screen.

**Comment by djdiskmachine** [comment]
I very much like the idea of having user-configurable scales, config.xml could be a good place for this as long as it doesn't cause issues for older versions.
The bigger question is about implementation. Being able to have individual scales per phrase is an _interesting_ idea, not necessarily a pain to implement.. However I'm a little bit skeptical about how user friendly this would be for the average, not Jazz-schooled, tracker user.

**Comment by clsource** [comment]
Maybe not scale per phrase but scale per project. In that way you can be on scale in every phrase.
So to ease things,  would be a global scale option that you can use to quickly enter notes within a scale.

One thing that would be cool but I dont know how to implement is playing the notes with an instrument, so when you select the scale or increase or decrease semitones you can hear how the instrument plays the notes.

**Comment by djdiskmachine** [comment]
Per project is no problem and very doable. Picotracker has this functionality already, maybe have a look over there for some inspiration ;)

I'd definitely vouch for scale selection in the project menu though. 

Note preview is added since 1.4.1

**Comment by clsource** [comment]
I was unable to compile picotracker also only found this related to scales https://github.com/xiphonics/picoTracker/issues/39

**Comment by maks** [comment]
@clsource picoTracker already has a working scales implementation.
As a starting point, look at the UI config for the feature in: https://github.com/xiphonics/picoTracker/blob/master/sources/Application/Views/ProjectView.cpp#L73-L81

**Comment by maks** [comment]
And yes likewise picoTracker has had not playback on change in the PhraseView for quite a long time now too, great job @djdiskmachine to see you added it in LGPT too 👍🏻

**Comment by clsource** [comment]
![imagen](https://github.com/user-attachments/assets/009464e1-302b-4e63-9a23-e93b1730d638)
![imagen](https://github.com/user-attachments/assets/efc767dc-25e7-498f-aa44-11536a6862b1)

**Comment by djdiskmachine** [comment]
> ![imagen](https://private-user-images.githubusercontent.com/292738/367592122-009464e1-302b-4e63-9a23-e93b1730d638.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0MTQ3NzcsIm5iZiI6MTcyNjQxNDQ3NywicGF0aCI6Ii8yOTI3MzgvMzY3NTkyMTIyLTAwOTQ2NGUxLTMwMmItNGU2My05YTIzLWU5M2IxNzMwZDYzOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxNVQxNTM0MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZGNmYTA5ZTg2OTFiMjI3Njg0ZDdlMmUzYTk5ODMyOWU5ZjRiMDJhOGJiYmY1Yzc5MDU5ZmQzYWU3ZDcxNGZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZoBA3KKhzb8QGS2XdDzKiOE0Z3FTvbgb-Qb36bx5qzI) ![imagen](https://private-user-images.githubusercontent.com/292738/367592144-efc767dc-25e7-498f-aa44-11536a6862b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0MTQ3NzcsIm5iZiI6MTcyNjQxNDQ3NywicGF0aCI6Ii8yOTI3MzgvMzY3NTkyMTQ0LWVmYzc2N2RjLTI1ZTctNDk4Zi1hYTQ0LTExNTM2YTY4NjJiMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxNVQxNTM0MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNGQzMzlmYTg0MTI0MWIxYjIyMmRkOThhMzA3YmQ5YmNiNGUxYTliOGZkYTE0ZGJhYzZlNzFmNDI4OTczNzg2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6TOq6zGZqSejRZ4hY-dNoZOSRRVlhv79lgG109-JAYE)

How does this look if adding a command in one of the fx columns?

**Comment by clsource** [comment]
![imagen](https://github.com/user-attachments/assets/8a0bd63e-d259-4126-bca6-8513bd666102)

Does not overlap :D

**Comment by djdiskmachine** [comment]
That's pretty busy looking. I'd like to keep this space as uncluttered as possible.

**Comment by clsource** [comment]
Ok how about this

![imagen](https://github.com/user-attachments/assets/2e9da636-0018-4f37-b4ee-4efe304d6062)

**Comment by djdiskmachine** [comment]
Two things:
1. I don't understand what this text adds to the feature seeing as scale selection already limits the note input to the notes in the scale.
2. I want as little text on screen as possible, and any text that is being displayed to be contextual. This is due to limited screen space, piggy supports many platforms and some have a smaller resolution than the desktop version you're using.

**Comment by clsource** [comment]
ok removed that feature.
but commented it in the code if someone wants to activate it 
by custom build.

**Comment by clsource** [comment]
Implemented
