### ISSUE TITLE
Nudging tempo down crashes the program

### ISSUE THREAD

**Issue by merumerutho** [djdiskmachine/LittleGPTracker#127]
Bug found in version 1.4.2 (tested on both Miyoo mini plus and W32 builds)

To reproduce:
1) Start playing a song 
2) Go to song settings menu and place cursor on tempo
3) Use B+arrow left to nudge tempo down 
4) If done for too long, the application will crash. 

My wild guess the tempo is nudged down to 0 and then it jumps to 0xFFFF (I havent checked if its an int or uint) or something because there is no logic to clamp to 0.

**Comment by djdiskmachine** [comment]
There's a nudge function? 🤯

**Comment by djdiskmachine** [comment]
Yup it's there on 1.4.2 for psp too, I'll get on it next week. 
Thx for the report and informing me of this feature! ♥️

**Comment by merumerutho** [comment]
To be fair, I also was unaware. Yesterday I got the idea: "Man, a nudge function would be amazing for DJ sets"
I was gonna feature request this but searched on the repo for "nudge"first  because I was unsure wheter it was there already. And suriprisingly enough there it was! 

Thanks for your work. I should really set up a build toolchain to help with the development sometimes.

**Comment by djdiskmachine** [comment]
Seems to me like there's an attack time  when releasing the button?
How bout we requirement this feature when were at it. I'd like arrow left/right to be fine adjustment and arrow up down coarse adjustment. =3

**Comment by djdiskmachine** [comment]
Skipping the coarse adjustment, I think it's useful as-is. 
Solved in https://github.com/djdiskmachine/LittleGPTracker/pull/130
