### ISSUE TITLE
[PSP] Soft clipping causes UI freeze and audio stutter

### ISSUE THREAD

**Issue by mrtnvgr** [djdiskmachine/LittleGPTracker#167]

**Comment by djdiskmachine** [comment]
Thanks for the report. Please include lgpt.log, platform configuration and steps how to reproduce.

**Comment by mrtnvgr** [comment]
Build version: `v1.4.3-bacon5 (latest master)`
Platform: `PSP E1000`

Steps to reproduce:
1. Open `lgpt_BETA` project
2. Change clipping mode to `subtle`

**Comment by mrtnvgr** [comment]
[lgpt.log](https://github.com/user-attachments/files/17606681/lgpt.log)

**Comment by purelygrey** [comment]
I don't have a psp, but maybe it's reproducible on an emulator, I'll try look into it

**Comment by djdiskmachine** [comment]
> I don't have a psp, but maybe it's reproducible on an emulator, I'll try look into it

Oh sorry i misremembered, thought you had a psp. Ppsspp does not intend to emulate psp hardware performance.

**Comment by mrtnvgr** [comment]
I would like to add that the issue happens even when there's only one note of a short sample being played :)

**Comment by djdiskmachine** [comment]
> I would like to add that the issue happens even when there's only one note of a short sample being played :)

With soft clipping enabled or is this a completely different freeze scenario?

**Comment by mrtnvgr** [comment]
> > I would like to add that the issue happens even when there's only one note of a short sample being played :)
> 
> With soft clipping enabled or is this a completely different freeze scenario?

With soft clipping enabled.

**Comment by purelygrey** [comment]
@mrtnvgr could you please try this build and see if it's any different? https://purelygrey.com/piggy/EBOOT.PBP

**Comment by purelygrey** [comment]
> > @mrtnvgr could you please try this build and see if it's any different? https://purelygrey.com/piggy/EBOOT.PBP
> 
> Nothing changed, PSP still lags...

Good, thanks :) Luckily enough it is reproducible in PPSSPP (at least when software rendering is on, it doesn't work at all otherwise on my laptop). I'll investigate more

**Comment by purelygrey** [comment]
@mrtnvgr try this one, same link: https://purelygrey.com/piggy/EBOOT.PBP
should work

**Comment by mrtnvgr** [comment]
> @mrtnvgr try this one, same link: https://purelygrey.com/piggy/EBOOT.PBP should work

Can confirm that this one works 🎉

**Comment by itsdarklikehell** [comment]
> > @mrtnvgr try this one, same link: https://purelygrey.com/piggy/EBOOT.PBP should work
> 
> Can confirm that this one works 🎉

I second this comment to add that testing on a PSP-2000 running latest ARK-4, it seems to work.

**Comment by djdiskmachine** [comment]
Solved in https://github.com/djdiskmachine/LittleGPTracker/pull/171
