### ISSUE TITLE
Change default buttons

### ISSUE THREAD

**Issue by djdiskmachine** [djdiskmachine/LittleGPTracker#20]
As a composer, I'd like a button layout like in Little Sound DJ by default.

This is 

- B button (X on PSP) as Option 
- A button (O on PSP) as Edit

**Comment by INFU-AV** [comment]
This might collide with logic set on rest of the console where "O" serves as exit button
I recommend setting B as "[ ]", and A as "X"

**Comment by djdiskmachine** [comment]
After closer investigation, the button assignment is completely misaligned between the platforms.
There's no simple way of doing this that won't break my brain and probably several configs.
Better to provide optional config.xml - files or possibly down the line reading gamecontrollerdb.txt
