### ISSUE TITLE
Noise/ clipping

### ISSUE THREAD

**Issue by ongofongo** [djdiskmachine/LittleGPTracker#37]
On the Anbernic RG280v there is constant noise and /or clipping, both with the sample project and new projects. Sometimes there are few clipping crackles, most of the time it’s too noisy to do anything really. Tried increasing the buffer size to 256 via config.xml. Tried with stock firmware as well as Rogue CFW and Adam Image.

**Comment by djdiskmachine** [comment]
How do you mean noisy? Can you provide an audio example?
I assume that a buffer of 256 is probably too small, try 512 and 1024 and see if it does any difference =)
