### ISSUE TITLE
GP2X build?

### ISSUE THREAD

**Issue by mbbmbbmm** [djdiskmachine/LittleGPTracker#38]
Any chance for GP2X builds including the new features?
I prefer GP2X over PSP for several reasons: MIDI ( sync with dirtywave M8), sound and the feel of the hardware

I could also try to build myself but not sure how to do that...

Is there a discord or forum to discuss/follow this project?

**Comment by djdiskmachine** [comment]
Sure! Check if there's still a toolchain available for gp2x and it should totally be compilable =)

**Comment by djdiskmachine** [comment]
This would be a good place to start.
http://wiki.gp2x.org/articles/i/n/s/Installing_the_Open2x_toolchain.html#Linux
Figured noone still had a working GP2X so I haven't put any effort in it. 
Try it out and get back to me if you get anywhere =)

**Comment by djdiskmachine** [comment]
Can't get the lib pack to download, seems lite building things with SDL is gonna be an issue :/
