### ISSUE TITLE
ignore irrelevant values when using config.xml psp 

### ISSUE THREAD

**Issue by diagrammatics** [djdiskmachine/LittleGPTracker#47]
It appears that the PSP build of 1.3o_alpha-5 fails to open when the "SCREENMULT" value is present in config.xml.

It would be helpful if the PSP build could ignore (presumably) irrelevant values when parsing config.xml, so users can maintain a single config.xml across platforms. Unsure if there are build-specific features like this already present.

**Comment by djdiskmachine** [comment]
Thanks for the report and sorry for the late reply.
I'll look into it
