### ISSUE TITLE
Miyoo: Double-assigned buttons from default keymap and mapping.xml

### ISSUE THREAD

**Issue by fpiesik** [djdiskmachine/LittleGPTracker#53]
There is a default keymap that is applied before the mapping.xml is loaded. Since Miyoo uses key commands instead of button commands, buttons function even without any assignments in the mapping.xml. However, this also means that the mappings in the mapping.xml conflict with the default ones, leading to buttons being double-assigned

**Comment by djdiskmachine** [comment]
Ah good catch!
So the mapping.xml should be edited to use key commands instead of button commands?

**Comment by fpiesik** [comment]
No, the mapping.xml for the Miyoo already uses key commands. I think the best approach would be to prevent the default mappings from being applied, so that only the mappings in the mapping.xml are applied.

**Comment by djdiskmachine** [comment]
OK I'll delete the provided mapping.xml for now as I don't have a device to test this out. Thanks for the report =)

**Comment by djdiskmachine** [comment]
Or wait, are you referring to this?
https://github.com/djdiskmachine/LittleGPTracker/blob/o-release-candidate/sources/Adapters/DINGOO/System/MIYOOSystem.cpp#L97

**Comment by fpiesik** [comment]
Yes, I think that is what's interfering with the mapping.xml.

**Comment by djdiskmachine** [comment]
If i attach a build without it, could you please help me verify if it works as intended? ☺️

**Comment by fpiesik** [comment]
would be an honor:)

**Comment by djdiskmachine** [comment]
[lgpt-miyoo-noinput.zip](https://github.com/djdiskmachine/LittleGPTracker/files/13845954/lgpt-miyoo-noinput.zip)
OK here we go
This requires a mapping.xml to be able to navigate, I'll research mapping further at a later stage =)

**Comment by fpiesik** [comment]
It works! This is now a really cool pocket setup - thanks:)

**Comment by djdiskmachine** [comment]
Asuuum!
Thousand thanks for helping out, I'll include this in the new release =D
