### ISSUE TITLE
Utilize status bar at the top

### ISSUE THREAD

**Issue by Ekolide** [djdiskmachine/LittleGPTracker#60]
Currently the row of text at the very top of the screen is used to display some information, but could display more.

For example, currently when saving a project, there is no feedback when it has finished. This could be remedied by displaying the messages "Saving..." then "Saved!" to update the user on the progress. 

The same thing applies to using commands like cut, copy, and paste. Currently it is hard to know if there is something in the cut/copy buffer, and whether or not a Copy command was successful. When the user enters selection mode, the status bar can inform the user by displaying "Selecting...", and then updating the user on what it's doing by displaying messages like "Cut!", "Copied!", or "Pasted!".

These messages could be displayed from the right edge, to avoid displaying over the information on the left side of the status row. Or to draw attention to itself, it could display on the left side, temporarily displaying over the information that was there.

**Comment by djdiskmachine** [comment]
This is good!
I'd like the field to also have a short description what the effects do.
