### ISSUE TITLE
Difference in Tuning Between Pre-Listened and Imported Samples

### ISSUE THREAD

**Issue by fpiesik** [djdiskmachine/LittleGPTracker#66]
Samples that are imported and used with default instrument settings are roughly one half step higher in pitch compared to how they sounded when previewed in the sample browser. Adjusting the detune to zero resolves this issue (although I'm not entirely sure if this results in the exact same tuning). However, the detune is intended to be neutral at 7f.

**Comment by djdiskmachine** [comment]
Just checked this on PPSSPP on Android, i don't hear it. What platform is producing this result?

**Comment by fpiesik** [comment]
Ah, that only applies to 48khz samples... are they supported anyway? 
I use Miyoo Mini.

**Comment by djdiskmachine** [comment]
Anything outside 44.1kHz, 16bit little-endian and you're on your own. Tread with caution ;)
