### ISSUE TITLE
Status of the project re. upstream and licensing

### ISSUE THREAD

**Issue by fgaz** [djdiskmachine/LittleGPTracker#71]
Hi! I'm the packager of upstream lgpt for [NixOS](https://nixos.org), and now that this fork got a stable release I'm considering it for inclusion/replacement of lgpt, but there are a couple issues stopping me.

1. The relationship of this project with upstream is unclear. "LittleGPTracker" is @Mdashdotdashn's project, having two projects with the same name is confusing. I can see two possible solutions.
    1. @Mdashdotdashn agrees to make you a maintainer of the upstream project, or nominates this fork as successor.
    2. The name of this fork is changed. It does not have to be totally different. It can be as simple as LittleGPTracker-ng or LittleGPTracker-enhanced.
2. Most importantly, the change to CC-BY-NC-SA is unfortunate, because it isn't a FOSS license due to the NC clause. It prevents inclusion in many distros, and [imposes heavy limitations](https://wiki.creativecommons.org/wiki/NonCommercial_interpretation#Choosing_NC_for_your_content). Furthermore, Creative Commons [is not recommended for code](https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software). Could you consider reverting to MIT while it's still possible, or switching to another FOSS license intended for code (GPL, EUPL, MPL, BSD...)?

**Comment by djdiskmachine** [comment]
Fair points! I'll look into changing the name of the repo, something like LittlePiggyTracker-featuredevelopment or something less long.

I'll look into which of those licenses fits best, Thanks for the recommendations :)

How have you handled building for x86_64 for NixOs?

**Comment by djdiskmachine** [comment]
Oh i just found this, that's great to know!
I'll apply this patch to my 64bit branch and check if soundfonts still work :)
https://github.com/NixOS/nixpkgs/blob/66a9817cec77098cfdcbb9ad82dbb92651987a84/pkgs/applications/audio/littlegptracker/0001-Remove-coherency-checks.patch#L12

**Comment by fgaz** [comment]
> I'll look into which of those licenses fits best, Thanks for the recommendations :)

Awesome, thank you for keeping the project FOSS!

> I'll look into changing the name of the repo

Looks like it won't be necessary! I emailed Marc, who agreed to join forces and make you a maintainer of upstream lgpt if you're ok with that.

> Oh i just found this, that's great to know!
> I'll apply this patch to my 64bit branch and check if soundfonts still work :)
> https://github.com/NixOS/nixpkgs/blob/66a9817cec77098cfdcbb9ad82dbb92651987a84/pkgs/applications/audio/littlegptracker/0001-Remove-coherency-checks.patch#L12

Yes that's it, and please do check! I'm not 100% sure it's ok, and the optimal way to fix it is probably to retype the library, as @Mdashdotdashn suggests here https://github.com/Mdashdotdashn/LittleGPTracker/issues/4#issuecomment-230245871

**Comment by peterswimm** [comment]
LittlePGTracker!

**Comment by djdiskmachine** [comment]
License set to FOSS-compliant
