### ISSUE TITLE
Color themes & user manual

### ISSUE THREAD

**Issue by ploupipoulpi** [djdiskmachine/LittleGPTracker#80]
Hi guys,

The old version had a txt file with a few example color themes, the one I had contained:
```
green
<BACKGROUND value="000000"/> <!-- BACKGROUND-->
<FOREGROUND value="44C7B6"/> <!-- song name -->
<HICOLOR1   value="145452"/> <!-- row count in song screen -->
<HICOLOR2   value="00FFF7"/> <!-- cursor-->
blue
<BACKGROUND value="000000"/> <!-- BACKGROUND-->
<FOREGROUND value="D1D1D1"/> <!-- song name -->
<HICOLOR1   value="35748B"/> <!-- row count in song screen -->
<HICOLOR2   value="2EB7D9"/> <!-- cursor-->
granate
<BACKGROUND value="070040"/> <!-- BACKGROUND-->
<FOREGROUND value="FF3333"/> <!-- song name -->
<HICOLOR1   value="8F1A35"/> <!-- row count in song screen -->
<HICOLOR2   value="FF4800"/> <!-- cursor-->
msdos
<BACKGROUND value="0F0099"/> <!-- BACKGROUND-->
<FOREGROUND value="DEDEDE"/> <!-- song name -->
<HICOLOR1   value="9C9C9C"/> <!-- row count in song screen -->
<HICOLOR2   value="FC6500"/> <!-- cursor-->
B/W
<BACKGROUND value="000000"/> <!-- BACKGROUND-->
<FOREGROUND value="FFFFFF"/> <!-- song name -->
<HICOLOR1   value="545454"/> <!-- row count in song screen -->
<HICOLOR2   value="A8A8A8"/> <!-- cursor-->
kammo
<BACKGROUND value="24230B"/> <!-- BACKGROUND-->
<FOREGROUND value="C2FFDA"/> <!-- song name -->
<HICOLOR1   value="415E22"/> <!-- row count in song screen -->
<HICOLOR2   value="09700C"/> <!-- cursor-->
```

There are new possible colors settings now:
```
  <BACKGROUND   value = "1D0A1F"/> <!--Background color-->
  <FOREGROUND   value = "F5EBFF"/> <!--Text color-->
  <HICOLOR1     value = "B750D1"/> <!--Highlight color 1-->
  <HICOLOR2     value = "DB33DB"/> <!--Highlight color 2-->
  <CURSORCOLOR  value = "FF00DD"/> <!--Cursor color-->
  <SONGVIEW_FE  value = "A55B8F" /> <!--Alt chain color1-->
  <SONGVIEW_00  value = "853B6F" /> <!--Alt chain color2-->
  <ROWCOLOR1    value = "BA28F9"/> <!--Row count color 1 -->
  <ROWCOLOR2    value = "FF00FF"/> <!--Row count color 2-->
  <ALTROWNUMBER value = "4"/>      <!--How many rows before alternating-->
```

I'm writing a simple shell script to allow picking a theme from a list when launching lgpt on the v90. I generally don't want the same color theme for light and dark environments, I have simple workarounds for that but I'd like to have something more versatile.
If you have new good color themes to propose, I can include them in what I'm doing.

Also, is there an updated version of the user manual somewhere? I could only find the wayback machine version there:
https://web.archive.org/web/20190721061112/http://wiki.littlegptracker.com/doku.php?id=lgpt:reference_manual#groove_screen
but maybe I'm missing something, I wouldn't want to redo something that has already been done by someone, please let me know if there is a better starting point for the User Manual, and if it's ok if I play around with it?

Thanks a lot!

**Comment by djdiskmachine** [comment]
Hey that's great!
You can check out some of the archived docs in here, please fill me in if you think something's missing =)

https://github.com/djdiskmachine/LittleGPTracker/tree/master/docs

**Comment by ploupipoulpi** [comment]
That's cool, better than the wayback version.

In the config xml page, one of the new colors is missing in the document, the example shows the new "CURSORCOLOR" but the explanation is missing it, and description of "HICOLOR2" is "cursor color" so that's confusing. 

I'll go through the whole thing as I'm making a kind of "operational guide" (removing install info, links and other things) that would be usable on the v90 screen as an ePub through Pixel reader. I'll attach the ePub result here once it's tested, and the source as HTML (I'm trying Sigil to make the ePub).

**Comment by djdiskmachine** [comment]
Please make a pull request whenever you get the time to finish this work =)
