### ISSUE TITLE
"Error Code: 139" When Launching Versions After 1.4.0 on Miyoo Mini Plus

### ISSUE THREAD

**Issue by imdkm** [djdiskmachine/LittleGPTracker#91]
Hi,

I encountered an issue with the Miyoo Mini Plus when trying to launch versions 1.4.0 and 1.4.1.

I attempted to launch version 1.4.1 on my Miyoo Mini Plus running Onion OS 1.4.3, but it failed to start and displayed the error message: "The program exited unexpectedly. Error code: 139."

The same issue occurred with version 1.4.0, but version 1.3o_2 works without any problems. I was able to load and play a sample song, as well as create a new song with version 1.3o_2.

Here is the log file for both versions 1.4.0 and 1.4.1 (they are identical):

```
[AUDIO] Audio object initialised with
[AUDIO] Api:
[AUDIO] Device:
[AUDIO] Buffer size:1024
[AUDIO] Pre Buffer Count:8
[CONFIG] Got value for ROOTFOLDER=/mnt/SDCARD/Tracks
[DISPLAY] Using driver fbcon. Screen (640,480) Bpp:32
[DISPLAY] Creating SDL Window (640,480)
[DISPLAY] Preparing fonts
[DISPLAY] Preparing font cache
[CONFIG] Got value for BACKGROUND=1D0A1F
[CONFIG] Got value for FOREGROUND=F5EBFF
[DISPLAY] Preparing full font cache
```

I am new to this kind of community and having almost no technical knowledges, so I apologize if this issue is not relevant.

Best regards,
imdkm

**Comment by djdiskmachine** [comment]
Thanks for your report, sorry for the late reply I was away for a few days. 
When you say it works with 1.3o_2, did you replace all of the files or just the binary? 

Log files are always great, however I can't see any reason for the crash from the dump you provided. 
Looks like the application starts to boot but fails for some reason. 

We're looking into it and will attempt to solve asap. :)

**Comment by djdiskmachine** [comment]
[lgpt-miyoo.elf.txt](https://github.com/user-attachments/files/16409671/lgpt-miyoo.elf.txt)
Please try this binary, remove .txt file ending, it was required for attaching in a comment.

**Comment by djdiskmachine** [comment]
Also, is this running on the card that came with the console?
I read some posts about this error showing up when using the sd card that was included in the box ☠️

**Comment by imdkm** [comment]
Thank you for your reply!

When I downgraded, I replaced all the files (except the samples and demo song). 

I'm using a new microSD card because my Miyoo Mini Plus was secondhand, and the seller didn't include one. I wonder if the error might be related to this situation, like if I somehow partially failed to install Onion OS or if my MMP has specific issues. Would it be worth re-installing the OS?

I tried the binary, but it didn't work; I got the same error and log file.

I've attached another logfile from the working 1.3o2 version for your reference. I hope this helps. Thanks.
[lgpt_1.3o_2.log.txt](https://github.com/user-attachments/files/16430508/lgpt_1.3o_2.log.txt)

**Comment by djdiskmachine** [comment]
Thanks for the log! 

I believe I've identified the issue, strange it wasn't caught earlier. Please try this bin when you have the opportunity :)

[lgpt-miyoo.elf.txt](https://github.com/user-attachments/files/16432887/lgpt-miyoo.elf.txt)

**Comment by imdkm** [comment]
I tried the fixed bin and it did work! Thank you very much.

**Comment by djdiskmachine** [comment]
Great news!
Thanks again for helping out. :)
