### ISSUE TITLE
[Request] MacOS build

### ISSUE THREAD

**Issue by clsource** [djdiskmachine/LittleGPTracker#92]
Hello, thanks for keeping alive this lovely tracker.
The current build only has OSX 32 bits, that cannot be run in newer MacOS 64 bits.

Please if a build can be made for macOS High Sierra 10.13.4 or newer 
it would be super awesome.

I think github actions can use macos versions for building artifacts.

Thanks again for this work of love ❤️

**Comment by clsource** [comment]
As far as I know there is some issues with SDL 1.2, it can be difficult to compile in newer OS versions.

https://github.com/libsdl-org/SDL-1.2

So for updating to newer OS the SDL version must be updated, but this would mean manny changes
and potentially loosing compatibility with older platforms such as PSP.

I tried to compile it though updated some of the libs and settings of Xcode to a newer one
but some changes has to be made in order to work.

![imagen](https://github.com/user-attachments/assets/da3e2318-cf68-4be9-88d4-593055924e0f)

**Comment by djdiskmachine** [comment]
Good news then! We have an SDL2 migration initiative going on by one of the contributors. It's apparently doable to use 1.2 for the platforms that don't support SDL2 like you mentioned. 

You can check up on the progress here:
https://github.com/simotek/LittleGPTracker/compare/refactor-build...simotek:LittleGPTracker:SDL2?expand=1

**Comment by djdiskmachine** [comment]
SDL + X64 migration is now merged to master. Feel free to fork and make a Pull Request if you'd like to contribute with a macOS port =)
